export const usStates: Map<string, string> = new Map([
  ['AL', 'Alabama'],
  ['AK', 'Alaska'],
  ['AZ', 'Arizona'],
  ['AR', 'Arkansas'],
  ['CA', 'California'],
  ['CO', 'Colorado'],
  ['CT', 'Connecticut'],
  ['DE', 'Delaware'],
  ['FL', 'Florida'],
  ['GA', 'Georgia'],
  ['HI', 'Hawaii'],
  ['ID', 'Idaho'],
  ['IL', 'Illinois'],
  ['IN', 'Indiana'],
  ['IA', 'Iowa'],
  ['KS', 'Kansas'],
  ['KY', 'Kentucky'],
  ['LA', 'Louisiana'],
  ['ME', 'Maine'],
  ['MD', 'Maryland'],
  ['MA', 'Massachusetts'],
  ['MI', 'Michigan'],
  ['MN', 'Minnesota'],
  ['MS', 'Mississippi'],
  ['MO', 'Missouri'],
  ['MT', 'Montana'],
  ['NE', 'Nebraska'],
  ['NV', 'Nevada'],
  ['NH', 'New Hampshire'],
  ['NJ', 'New Jersey'],
  ['NM', 'New Mexico'],
  ['NY', 'New York'],
  ['NC', 'North Carolina'],
  ['ND', 'North Dakota'],
  ['OH', 'Ohio'],
  ['OK', 'Oklahoma'],
  ['OR', 'Oregon'],
  ['PA', 'Pennsylvania'],
  ['RI', 'Rhode Island'],
  ['SC', 'South Carolina'],
  ['SD', 'South Dakota'],
  ['TN', 'Tennessee'],
  ['TX', 'Texas'],
  ['UT', 'Utah'],
  ['VT', 'Vermont'],
  ['VA', 'Virginia'],
  ['WA', 'Washington'],
  ['WV', 'West Virginia'],
  ['WI', 'Wisconsin'],
  ['WY', 'Wyoming'],
]);

export const stateSalesTax: Map<string, string> = new Map<string, string>([
  ['Alabama', '.04'],
  ['Alaska', '0'],
  ['Arizona', '.056'],
  ['Arkansas', '.065'],
  ['California', '.0825'],
  ['Colorado', '.029'],
  ['Connecticut', '.0635'],
  ['Delaware', '0'],
  ['Florida', '.06'],
  ['Georgia', '.04'],
  ['Hawaii', '.04'],
  ['Idaho', '.06'],
  ['Illinois', '.0625'],
  ['Indiana', '.07'],
  ['Iowa', '.06'],
  ['Kansas', '.065'],
  ['Kentucky', '.06'],
  ['Louisiana', '.04'],
  ['Maine', '.055'],
  ['Maryland', '.06'],
  ['Massachusetts', '.0625'],
  ['Michigan', '.06'],
  ['Minnesota', '.06875'],
  ['Mississippi', '.07'],
  ['Missouri', '.04225'],
  ['Montana', '0'],
  ['Nebraska', '.055'],
  ['Nevada', '.0685'],
  ['New Hampshire', '0'],
  ['New Jersey', '.06625'],
  ['New Mexico', '.05125'],
  ['New York', '.04'],
  ['North Carolina', '.0475'],
  ['North Dakota', '.05'],
  ['Ohio', '.0575'],
  ['Oklahoma', '.045'],
  ['Oregon', '0'],
  ['Pennsylvania', '.06'],
  ['Rhode Island', '.07'],
  ['South Carolina', '.06'],
  ['South Dakota', '0'],
  ['Tennessee', '.07'],
  ['Texas', '.0625'],
  ['Utah', '.047'],
  ['Vermont', '.06'],
  ['Virginia', '.043'],
  ['Washington', '.065'],
  ['West Virginia', '.06'],
  ['Wisconsin', '.05'],
  ['Wyoming', '.04'],
]);
