import { Product } from './models/product';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "RoastMaster's Reserve",
    price: 23.99,
    imgSrc: 'coffee-bag-1.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#7db2c0',
  },
  {
    id: 2,
    name: 'Bean Bliss',
    price: 21.99,
    imgSrc: 'coffee-bag-2.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#d8944f',
  },
  {
    id: 3,
    name: 'Caffeine Cascade',
    price: 19.99,
    imgSrc: 'coffee-bag-3.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#11652d',
  },
  {
    id: 4,
    name: 'Mocha Marvel',
    price: 23.99,
    imgSrc: 'coffee-bag-4.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#099683',
  },
  {
    id: 5,
    name: 'Velvet Roast',
    price: 21.99,
    imgSrc: 'coffee-bag-5.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#790654',
  },
  {
    id: 6,
    name: 'Java Jive',
    price: 19.99,
    imgSrc: 'coffee-bag-6.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#634636',
  },
  {
    id: 7,
    name: 'Espresso Euphoria',
    price: 23.99,
    imgSrc: 'coffee-bag-7.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#af754d',
  },
  {
    id: 8,
    name: 'Flavorful Fusion',
    price: 21.99,
    imgSrc: 'coffee-bag-8.png',
    type: 'coffee',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
    color: '#a25016',
  },
  {
    id: 9,
    name: 'Gift Card- $25',
    price: 25,
    imgSrc: 'gift-card-25.png',
    type: 'card',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
  },
  {
    id: 10,
    name: 'Gift Card- $50',
    price: 50,
    imgSrc: 'gift-card-50.png',
    type: 'card',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
  },
  {
    id: 11,
    name: 'Gift Card- $75',
    price: 75,
    imgSrc: 'gift-card-75.png',
    type: 'card',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
  },
  {
    id: 12,
    name: 'Gift Card- $100',
    price: 100,
    imgSrc: 'gift-card-100.png',
    type: 'card',
    desc: 'We have been importing this Organic coffee direct from the cooperative Taramesa in the region of Sidama with our colleague from Roasters United for several years now. This coffee is very delicate, fruity with a fresh finish. It is very interesting also in light roast for V60, aeropress, etc. It is more on the blue fruits side than on the espresso roast. This coffee is organic certified by bio-inspecta.',
  },
];
